[package]
name = "cobertura"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
coverage = { path = "../coverage" }
debuggable-module = { path = "../debuggable-module" }
quick-xml = "0.26.0"
